### ISSUE TITLE
Unhandled exception when running a match of my own tree with an early copy of itself

### ISSUE THREAD

**Issue by ennoborg** [andersardo/gramps_Treemerge#1]
When I try to match my tree with an imported copy, which is probably an early generation, or a copy downloaded from Ancestry, I get this:

363812: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "/home/enno/.gramps/gramps52/plugins/Treemerge/treemerge.py", line 204, in do_match
    matcher.do_find_matches()
  File "/home/enno/.gramps/gramps52/plugins/Treemerge/match.py", line 100, in do_find_matches
    self.find_potentials(self.threshold)
  File "/home/enno/.gramps/gramps52/plugins/Treemerge/match.py", line 191, in find_potentials
    for hit in self.ftdb.getMatchesForHandle(p1key):
  File "/home/enno/.gramps/gramps52/plugins/Treemerge/ftDatabase.py", line 62, in getMatchesForHandle
    res = searcher.search(q, limit=ant, terms=False)
  File "/usr/lib/python3/dist-packages/whoosh/searching.py", line 786, in search
    self.search_with_collector(q, c)
  File "/usr/lib/python3/dist-packages/whoosh/searching.py", line 819, in search_with_collector
    collector.run()
  File "/usr/lib/python3/dist-packages/whoosh/collectors.py", line 143, in run
    self.set_subsearcher(subsearcher, offset)
  File "/usr/lib/python3/dist-packages/whoosh/collectors.py", line 171, in set_subsearcher
    self.matcher = self.q.matcher(subsearcher, self.context)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 211, in matcher
    m = self._matcher(subs, searcher, context)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 270, in _matcher
    context, q_weight_fn)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 226, in _tree_matcher
    subms = [q.matcher(searcher, context) for q in subs]
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 226, in <listcomp>
    subms = [q.matcher(searcher, context) for q in subs]
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 211, in matcher
    m = self._matcher(subs, searcher, context)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 369, in _matcher
    scale=self.scale).matcher(searcher, context)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 211, in matcher
    m = self._matcher(subs, searcher, context)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 379, in _matcher
    q_weight_fn)
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 226, in _tree_matcher
    subms = [q.matcher(searcher, context) for q in subs]
  File "/usr/lib/python3/dist-packages/whoosh/query/compound.py", line 226, in <listcomp>
    subms = [q.matcher(searcher, context) for q in subs]
  File "/usr/lib/python3/dist-packages/whoosh/query/positional.py", line 226, in matcher
    % self.fieldname)
whoosh.query.qcore.QueryError: Phrase search: 'person' field has no positions

**Comment by andersardo** [comment]
Might be reserved characters in somewhere in the database that plays havoc with the freetext database Woosh.
I have added some cleaning of all text before it's indexed.

**Comment by ennoborg** [comment]
OK, that helped, and I like the graph view that I see when I click Merge. I didn't see any merging being done, but maybe that's because you didn't implement that part yet.

I got one new error, on close, I think:

grok button clicked
2022-01-29 20:44:11.229: ERROR: grampsapp.py: line 157: Unhandled exception
TypeError: close() takes 2 positional arguments but 3 were given

**Comment by andersardo** [comment]
Close of ManagedWindows should work now.

I have also enabled calling the Gramps MergePerson functionality.
